name: Secret Workflow Example

on:
  push:
    branches:
      - master

jobs:
  run-secret-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use the secret securely
      run: |
        echo "The secret is ${{ secrets.SECRET }}"
      env:
        SECRET: ${{ secrets.SECRET }}

